FROM debian:stretch-slim
# FROM nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04
RUN apt-get update \
    && apt-get install -y git python3 python3-pip \
        wget libncurses5-dev zlib1g-dev libbz2-dev liblzma-dev libcurl3-dev python3-pandas\
    && apt-get clean

RUN pip3 install numpy==1.16.1 \
    && pip3 install h5py==2.10.0 \
    && pip3 install keras==2.1.2 \
    && pip3 install tensorflow==1.12.0 \
#    && pip3 install tensorflow-gpu==1.4.0 \
    && pip3 install tqdm

RUN cpan Statistics::Basic

# WORKDIR /usr/src
# #Samtools
# RUN wget https://github.com/samtools/samtools/releases/download/1.12/samtools-1.12.tar.bz2 \
#     && tar jxf samtools-1.12.tar.bz2 \
#     && rm samtools-1.12.tar.bz2 \
#     && cd samtools-1.12 \
#     && ./configure --prefix $(pwd) \
#     && make
# #bwa
# RUN wget https://pilotfiber.dl.sourceforge.net/project/bio-bwa/bwa-0.7.17.tar.bz2 \
#     && tar jxf bwa-0.7.17.tar.bz2 \
#     && rm bwa-0.7.17.tar.bz2 \
#     && cd bwa-0.7.17 \
#     && make
# ENV PATH=${PATH}:/usr/src/samtools-1.12:/usr/src/bwa-0.7.17

# conda
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/src/miniconda3 \
    && rm -f Miniconda3-latest-Linux-x86_64.sh 
ENV PATH=${PATH}:/usr/src/miniconda3/bin

RUN conda config --add channels bioconda \
    && conda install -y -c bioconda bwa samtools=1.9 pbmm2

RUN mkdir /cuhk/
ADD bin /cuhk
